vim.opt.background = 'dark'
-- local highlight = require('util').highlight
--
-- function _G.OverrideHighlights()
--     highlight('Normal',          {ctermfg = 250, ctermbg = 235, guifg = '#e1e3e4', guibg = '#232627'}, false)
--     highlight('EndOfBuffer',     {ctermfg = 250, ctermbg = 235, guifg = '#e1e3e4', guibg = '#232627'}, false)
--     highlight('SignColumn',      {ctermfg = 250, ctermbg = 235, guifg = '#e1e3e4', guibg = '#232627'}, false)
--     highlight('Tabline',         {ctermfg = 250, ctermbg = 235, guifg = '#e1e3e4', guibg = '#232627'}, false)
--     highlight('TablineFill',     {ctermfg = 250, ctermbg = 235, guifg = '#e1e3e4', guibg = '#232627'}, false)
--     highlight('BlueSign',        {ctermfg = 110, ctermbg = 236, guifg = '#6dcae8', guibg = '#232627'}, false)
--     highlight('GreenSign',       {ctermfg = 107, ctermbg = 236, guifg = '#9ed06c', guibg = '#232627'}, false)
--     highlight('RedSign',         {ctermfg = 203, ctermbg = 236, guifg = '#fb617e', guibg = '#232627'}, false)
--
--     -- remove the background of the vertical splitter
--     highlight('VertSplit',       {ctermbg = 'NONE', guibg = 'NONE'}, false)
--     highlight('Visual',          {cterm = 'bold', ctermbg = 'Blue', guibg = '#41444F'}, false)
--     highlight('Search',          {ctermfg = 236, ctermbg = 180, guifg = '#282c34', guibg = '#5992F0', gui = 'italic,underline,bold'}, false)
--     highlight('IncSearch',       {guibg = '#E388D5', ctermbg = 'green', term = 'underline'}, false)
--     highlight('VertSplit',       {ctermfg = 237, guifg = '#888822'}, false)
--     highlight('ExtraWhitespace', {ctermbg = 'red', guibg = 'red'}, false)
--     highlight('ColorColumn',     {ctermbg = 52, guibg = '#2E2A2A'}, false)
--
--     -- popups
--     highlight('Pmenu',           {guibg = '#3B404D', ctermbg = 236, guifg = '#dcdfe4', ctermfg=188}, false)
--
--     highlight('ALEError',        {ctermbg = 167, ctermfg = 'Black'}, false)
--     highlight('ALEWarning',      {ctermbg = 179, ctermfg = 'Black'}, false)
--
--     -- Terminal colours.
--     vim.api.nvim_del_var('terminal_color_0')
--     vim.api.nvim_del_var('terminal_color_1')
--     vim.api.nvim_del_var('terminal_color_2')
--     vim.api.nvim_del_var('terminal_color_3')
--     vim.api.nvim_del_var('terminal_color_4')
--     vim.api.nvim_del_var('terminal_color_5')
--     vim.api.nvim_del_var('terminal_color_6')
--     vim.api.nvim_del_var('terminal_color_7')
--     vim.api.nvim_del_var('terminal_color_8')
--     vim.api.nvim_del_var('terminal_color_9')
--     vim.api.nvim_del_var('terminal_color_10')
--     vim.api.nvim_del_var('terminal_color_11')
--     vim.api.nvim_del_var('terminal_color_12')
--     vim.api.nvim_del_var('terminal_color_13')
--     vim.api.nvim_del_var('terminal_color_14')
--     vim.api.nvim_del_var('terminal_color_15')
-- end
--
-- vim.api.nvim_command([[
-- augroup OverrideSonokaiColors
--     autocmd ColorScheme sonokai call v:lua.OverrideHighlights()
-- augroup END
-- ]])

vim.opt.guifont = 'DejaVuSansMono Nerd Font:h10'
vim.cmd([[colorscheme arsham]])
-- vim.cmd([[colorscheme sonokai]])
