vim.opt_local.expandtab = true
vim.opt_local.tabstop = 2
vim.opt_local.softtabstop = 2
vim.opt_local.shiftwidth = 2
vim.opt_local.formatoptions:remove({ "t", "c" })

-- stylua: ignore start
vim.api.nvim_command("iabbrev <buffer> as         AS")
vim.api.nvim_command("iabbrev <buffer> by         BY")
vim.api.nvim_command("iabbrev <buffer> cascade    CASCADE")
vim.api.nvim_command("iabbrev <buffer> create     CREATE")
vim.api.nvim_command("iabbrev <buffer> delete     DELETE")
vim.api.nvim_command("iabbrev <buffer> drop       DROP")
vim.api.nvim_command("iabbrev <buffer> else       ELSE")
vim.api.nvim_command("iabbrev <buffer> end        END")
vim.api.nvim_command("iabbrev <buffer> foreign    FOREIGN")
vim.api.nvim_command("iabbrev <buffer> from       FROM")
vim.api.nvim_command("iabbrev <buffer> group      GROUP")
vim.api.nvim_command("iabbrev <buffer> having     HAVING")
vim.api.nvim_command("iabbrev <buffer> index      INDEX")
vim.api.nvim_command("iabbrev <buffer> insert     INSERT")
vim.api.nvim_command("iabbrev <buffer> into       INTO")
vim.api.nvim_command("iabbrev <buffer> join       JOIN")
vim.api.nvim_command("iabbrev <buffer> key        KEY")
vim.api.nvim_command("iabbrev <buffer> limit      LIMIT")
vim.api.nvim_command("iabbrev <buffer> offset     OFFSET")
vim.api.nvim_command("iabbrev <buffer> on         ON")
vim.api.nvim_command("iabbrev <buffer> order      ORDER")
vim.api.nvim_command("iabbrev <buffer> primary    PRIMARY")
vim.api.nvim_command("iabbrev <buffer> references REFERENCES")
vim.api.nvim_command("iabbrev <buffer> select     SELECT")
vim.api.nvim_command("iabbrev <buffer> set        SET")
vim.api.nvim_command("iabbrev <buffer> table      TABLE")
vim.api.nvim_command("iabbrev <buffer> then       THEN")
vim.api.nvim_command("iabbrev <buffer> union      UNION")
vim.api.nvim_command("iabbrev <buffer> unique     UNIQUE")
vim.api.nvim_command("iabbrev <buffer> update     UPDATE")
vim.api.nvim_command("iabbrev <buffer> values     VALUES")
vim.api.nvim_command("iabbrev <buffer> when       WHEN")
vim.api.nvim_command("iabbrev <buffer> where      WHERE")
-- stylua: ignore end
